# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
        my_config:
            toolbar: "full"
    toolbars:
        items:
            full.colors: [ "TextColor", "BGColor" ]
            full.document: [ "Source", "-", "Preview", "Print" ]